### ISSUE TITLE
Doesn't work with plone 5.2.4-py3 (but works with plone 5.2.1-py3)

### ISSUE THREAD

**Issue by oggers** [collective/collective.celery#17]
When executing pcelery it raises this error:

`Traceback (most recent call last):`
`  File "/usr/local/plone-5.2-py3/apymtest_5_2_py3/bin/pcelery", line 309, in <module>`
`    sys.exit(collective.celery.scripts.ccelery.main())`
`  File "/usr/local/plone-5.2-py3/buildout-cache/eggs/collective.celery-1.1.4-py3.6.egg/collective/celery/scripts/ccelery.py", line 42, in main`
`    from Zope2.Startup.run import configure`
`  File "/usr/local/plone-5.2-py3/buildout-cache/eggs/zope.deferredimport-4.3.1-py3.6.egg/zope/deferredimport/deferredmodule.py", line 70, in __getattr__`
`    v = get.get()`
`  File "/usr/local/plone-5.2-py3/buildout-cache/eggs/zope.deferredimport-4.3.1-py3.6.egg/zope/deferredimport/deferredmodule.py", line 54, in get`
`    return super(DeferredAndDeprecated, self).get()`
`  File "/usr/local/plone-5.2-py3/buildout-cache/eggs/zope.deferredimport-4.3.1-py3.6.egg/zope/deferredimport/deferredmodule.py", line 37, in get`
`    v = __import__(module, *self._import_chicken)`
`ModuleNotFoundError: No module named 'ZServer' `

**Comment by ale-rt** [comment]
Maybe you were using it Plone 5.2.1 and Python2.7...
AFAIK there is no released version of ZServer supporting Python 3...

You might have some luck trying @datakurre's fork https://github.com/datakurre/ZServer

Just in case, please consider changing the title of the issue :)

**Comment by oggers** [comment]
Sorry, you're right. I forgot to install a manual patch in order to work on py3.

Here is the patch if someone is interested in it:
```
--- collective/celery/scripts/ccelery.py.orig	2019-08-01 16:00:18.252966624 +0200
+++ collective/celery/scripts/ccelery.py	2019-08-11 22:39:13.523831872 +0200
@@ -1,6 +1,7 @@
 # a lot of this pulled out of pyramid_celery
 from importlib import import_module
 import os
+import six
 import sys
 
 from App.config import getConfiguration
@@ -39,8 +40,24 @@
     filepath = sys.argv[conf_index]
     os.environ['ZOPE_CONFIG'] = filepath
     sys.argv = ['']
-    from Zope2.Startup.run import configure
-    startup = configure(os.environ['ZOPE_CONFIG'])
+    if '--wsgi' in argv or '-w' in argv:
+        try:
+            idx = argv.index('--wsgi')
+        except ValueError:
+            idx = argv.index('-w')
+        opt = argv[idx + 1:idx + 2]
+        if opt:
+            wsgi = opt[0].lower() in ('off', 'false', '0')
+        else:
+            wsgi = True
+    else:
+        wsgi = False
+    if six.PY2 and not wsgi:
+        from Zope2.Startup.run import configure
+        startup = configure(os.environ['ZOPE_CONFIG'])
+    else:
+        from Zope2.Startup.run import configure_wsgi
+        startup = configure_wsgi(os.environ['ZOPE_CONFIG'])
 
     # Fix for setuptools generated scripts, so that it will
     # work with multiprocessing fork emulation.
--- collective.orig/celery/base_task.py    2019-10-12 20:50:24.033162691 +0200
+++ collective/celery/base_task.py 2019-11-11 22:32:16.861026379 +0100
@@ -87,8 +87,10 @@
     # set object paths instead of objects
     def apply_async(self, args, kwargs, **options):
         args, kw = self.serialize_args(args, kwargs)
-        kw['site_path'] = '/'.join(api.portal.get().getPhysicalPath())
-        kw['authorized_userid'] = api.user.get_current().getId()
+        if 'site_path' not in kw:
+            kw['site_path'] = '/'.join(api.portal.get().getPhysicalPath())
+        if 'authorized_userid' not in kw:
+            kw['authorized_userid'] = api.user.get_current().getId()
 
         without_transaction = options.pop('without_transaction', False)
```

**Comment by ale-rt** [comment]
Thanks for sharing!
