### ISSUE TITLE
Only WARN messages get logged, no INFO message

### ISSUE THREAD

**Issue by MrTango** [collective/collective.celery#9]
If I get it right, the worker use the zope.conf settings and should therefore have the loglevel INFO.
But I can only see WARN messages in the log no INFO message get's there.
How can I fix that?

**Comment by petschki** [comment]
start the worker with `bin/pcelery worker <configfile> --loglevel=INFO` ... seems that the zope.conf settings aren't used here

**Comment by MrTango** [comment]
@petschki thx for the info. But i switched meanwhile to collective.taskqueue which is much easier to debug and handle does needed job very well for me.
